version: '3.8'

services:
  casadin-backend:
    build: .
    container_name: casadin-backend
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    working_dir: /app
    command: npm run start:dev
    networks:
      - app-network

  casadin-frontend:
    image: node:20-alpine
    container_name: casadin-frontend
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm run dev
    volumes:
      - ../casadin-frontend:/app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - casadin-backend
      - casadin-frontend
    networks:
      - app-network

  database:
    image: postgres
    container_name: casadin-database
    environment:
      POSTGRES_USER: casadin
      POSTGRES_PASSWORD: casadin
      POSTGRES_DB: casadin_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  app-network:

volumes:
  db_data: